global using static Game.Server.AI_ConditionGlobals;

using Source;

using System.Runtime.CompilerServices;

namespace Game.Server;

public static class AI_ConditionGlobals
{
	public const int MAX_CONDITIONS = 32 * 8;
}

public enum SCOND_t
{
	COND_NONE,
	COND_IN_PVS,
	COND_IDLE_INTERRUPT,
	COND_LOW_PRIMARY_AMMO,
	COND_NO_PRIMARY_AMMO,
	COND_NO_SECONDARY_AMMO,
	COND_NO_WEAPON,
	COND_SEE_HATE,
	COND_SEE_FEAR,
	COND_SEE_DISLIKE,
	COND_SEE_ENEMY,
	COND_LOST_ENEMY,
	COND_ENEMY_WENT_NULL,
	COND_ENEMY_OCCLUDED,
	COND_TARGET_OCCLUDED,
	COND_HAVE_ENEMY_LOS,
	COND_HAVE_TARGET_LOS,
	COND_LIGHT_DAMAGE,
	COND_HEAVY_DAMAGE,
	COND_PHYSICS_DAMAGE,
	COND_REPEATED_DAMAGE,
	COND_CAN_RANGE_ATTACK1,
	COND_CAN_RANGE_ATTACK2,
	COND_CAN_MELEE_ATTACK1,
	COND_CAN_MELEE_ATTACK2,
	COND_PROVOKED,
	COND_NEW_ENEMY,
	COND_ENEMY_TOO_FAR,
	COND_ENEMY_FACING_ME,
	COND_BEHIND_ENEMY,
	COND_ENEMY_DEAD,
	COND_ENEMY_UNREACHABLE,
	COND_SEE_PLAYER,
	COND_LOST_PLAYER,
	COND_SEE_NEMESIS,
	COND_TASK_FAILED,
	COND_SCHEDULE_DONE,
	COND_SMELL,
	COND_TOO_CLOSE_TO_ATTACK,
	COND_TOO_FAR_TO_ATTACK,
	COND_NOT_FACING_ATTACK,
	COND_WEAPON_HAS_LOS,
	COND_WEAPON_BLOCKED_BY_FRIEND,
	COND_WEAPON_PLAYER_IN_SPREAD,
	COND_WEAPON_PLAYER_NEAR_TARGET,
	COND_WEAPON_SIGHT_OCCLUDED,
	COND_BETTER_WEAPON_AVAILABLE,
	COND_HEALTH_ITEM_AVAILABLE,
	COND_GIVE_WAY,
	COND_WAY_CLEAR,
	COND_HEAR_DANGER,
	COND_HEAR_THUMPER,
	COND_HEAR_BUGBAIT,
	COND_HEAR_COMBAT,
	COND_HEAR_WORLD,
	COND_HEAR_PLAYER,
	COND_HEAR_BULLET_IMPACT,
	COND_HEAR_PHYSICS_DANGER,
	COND_HEAR_MOVE_AWAY,
	COND_HEAR_SPOOKY,
	COND_NO_HEAR_DANGER,
	COND_FLOATING_OFF_GROUND,
	COND_MOBBED_BY_ENEMIES,
	COND_RECEIVED_ORDERS,
	COND_PLAYER_ADDED_TO_SQUAD,
	COND_PLAYER_REMOVED_FROM_SQUAD,
	COND_PLAYER_PUSHING,
	COND_NPC_FREEZE,
	COND_NPC_UNFREEZE,
	COND_TALKER_RESPOND_TO_QUESTION,
	COND_NO_CUSTOM_INTERRUPTS,
	LAST_SHARED_CONDITION
}

[InlineArray(MAX_CONDITIONS >> 3)]
public struct AI_ScheduleBits
{
	public byte bytes;
	public void ClearAll() => BitVecBase.ClearAll(this);
	public void SetAll() => ((Span<byte>)this).Fill(0xff);
	public void Set(int bit) => BitVecBase.Set(this, bit);
	public void Clear(int bit) => BitVecBase.Clear(this, bit);
	public bool IsBitSet(int bit) => BitVecBase.IsBitSet(this, bit);
}
