<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<Configurations>Debug;Release;Debug (Dedicated);Release (Dedicated)</Configurations>
		<OutputPath>bin\$(Configuration)\</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Source.Common\Source.Common.csproj" />
		<ProjectReference Include="..\Source.CodeAnalysis.BitVec\Source.CodeAnalysis.BitVec.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\Source.CodeAnalysis.NetworkVars\Source.CodeAnalysis.NetworkVars.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="xunit.v3" Version="4.0.1" />
	</ItemGroup>

</Project>
