using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using System.Linq;
using System.Text;

namespace Source.CodeAnalysis.BitVec
{
	[Generator(LanguageNames.CSharp)]
	public sealed class BitVecGenerator : IIncrementalGenerator
	{
		private const string AttributeMetadataName = "Source.BitVecAttribute";
		private const string GenericAttributeMetadataName = "Source.BitVecAttribute`1";

		private static readonly DiagnosticDescriptor NotPartial = new DiagnosticDescriptor(
			id: "BITVEC001",
			title: "[BitVec] requires a partial struct",
			messageFormat: "'{0}' is marked [BitVec] but is not partial; the generator cannot emit its storage and members",
			category: "BitVec",
			defaultSeverity: DiagnosticSeverity.Error,
			isEnabledByDefault: true);

		private static readonly DiagnosticDescriptor Unsupported = new DiagnosticDescriptor(
			id: "BITVEC002",
			title: "[BitVec] only supports top-level non-generic structs",
			messageFormat: "'{0}' is marked [BitVec] but is nested or generic, which is not supported",
			category: "BitVec",
			defaultSeverity: DiagnosticSeverity.Error,
			isEnabledByDefault: true);

		private static readonly DiagnosticDescriptor InvalidArguments = new DiagnosticDescriptor(
			id: "BITVEC003",
			title: "[BitVec] has invalid arguments",
			messageFormat: "'{0}' is marked [BitVec] with an invalid bit count or word type",
			category: "BitVec",
			defaultSeverity: DiagnosticSeverity.Error,
			isEnabledByDefault: true);

		private sealed class Model
		{
			public string? Namespace = null;
			public string Name = "";
			public string WordType = "uint";
			public int BitsPerWord = 32;
			public int NumBits;
			public Diagnostic? Error;
		}

		public void Initialize(IncrementalGeneratorInitializationContext context) {
			IncrementalValuesProvider<Model> plain = context.SyntaxProvider.ForAttributeWithMetadataName(
				AttributeMetadataName,
				static (node, _) => node is StructDeclarationSyntax,
				static (ctx, _) => CreateModel(ctx));

			IncrementalValuesProvider<Model> generic = context.SyntaxProvider.ForAttributeWithMetadataName(
				GenericAttributeMetadataName,
				static (node, _) => node is StructDeclarationSyntax,
				static (ctx, _) => CreateModel(ctx));

			context.RegisterSourceOutput(plain, static (spc, model) => Emit(spc, model));
			context.RegisterSourceOutput(generic, static (spc, model) => Emit(spc, model));
		}

		private static Model CreateModel(GeneratorAttributeSyntaxContext ctx) {
			INamedTypeSymbol symbol = (INamedTypeSymbol)ctx.TargetSymbol;
			StructDeclarationSyntax syntax = (StructDeclarationSyntax)ctx.TargetNode;
			Model model = new Model { Name = symbol.Name };

			if (!syntax.Modifiers.Any(m => m.Text == "partial")) {
				model.Error = Diagnostic.Create(NotPartial, syntax.Identifier.GetLocation(), symbol.Name);
				return model;
			}

			if (symbol.ContainingType != null || symbol.IsGenericType) {
				model.Error = Diagnostic.Create(Unsupported, syntax.Identifier.GetLocation(), symbol.Name);
				return model;
			}

			model.Namespace = symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString();

			AttributeData attribute = ctx.Attributes[0];
			if (attribute.ConstructorArguments.Length != 1 || !(attribute.ConstructorArguments[0].Value is int numBits) || numBits <= 0) {
				model.Error = Diagnostic.Create(InvalidArguments, syntax.Identifier.GetLocation(), symbol.Name);
				return model;
			}
			model.NumBits = numBits;

			INamedTypeSymbol? attributeClass = attribute.AttributeClass;
			if (attributeClass != null && attributeClass.IsGenericType) {
				ITypeSymbol wordType = attributeClass.TypeArguments[0];
				switch (wordType.SpecialType) {
					case SpecialType.System_Byte: model.WordType = "byte"; model.BitsPerWord = 8; break;
					case SpecialType.System_UInt16: model.WordType = "ushort"; model.BitsPerWord = 16; break;
					case SpecialType.System_UInt32: model.WordType = "uint"; model.BitsPerWord = 32; break;
					case SpecialType.System_UInt64: model.WordType = "ulong"; model.BitsPerWord = 64; break;
					default:
						model.Error = Diagnostic.Create(InvalidArguments, syntax.Identifier.GetLocation(), symbol.Name);
						return model;
				}
			}

			return model;
		}

		private static void Emit(SourceProductionContext spc, Model model) {
			if (model.Error != null) {
				spc.ReportDiagnostic(model.Error);
				return;
			}

			int numWords = (model.NumBits + model.BitsPerWord - 1) / model.BitsPerWord;
			string name = model.Name;
			string word = model.WordType;
			string ops = $"global::Source.BitSetOps<{word}>";

			StringBuilder sb = new StringBuilder();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("#nullable enable");
			sb.AppendLine();
			if (model.Namespace != null) {
				sb.AppendLine($"namespace {model.Namespace};");
				sb.AppendLine();
			}
			sb.AppendLine($"[global::System.Runtime.CompilerServices.InlineArray({numWords})]");
			sb.AppendLine($"partial struct {name} : global::System.IEquatable<{name}>");
			sb.AppendLine("{");
			sb.AppendLine($"\tprivate {word} _word;");
			sb.AppendLine();
			sb.AppendLine($"\tpublic const int NumBits = {model.NumBits};");
			sb.AppendLine();
			sb.AppendLine($"\tpublic readonly {word} GetWord(int i) => {ops}.GetWord(this, i);");
			sb.AppendLine($"\tpublic void SetWord(int i, {word} val) => {ops}.SetWord(this, i, val);");
			sb.AppendLine($"\tpublic readonly int GetNumWords() => {ops}.GetNumWords(this);");
			sb.AppendLine($"\tpublic readonly int Get(int bit) => {ops}.IsBitSet(this, bit) ? 1 : 0;");
			sb.AppendLine($"\tpublic readonly bool IsBitSet(int bit) => {ops}.IsBitSet(this, bit);");
			sb.AppendLine($"\tpublic void Set(int bit) => {ops}.Set(this, bit);");
			sb.AppendLine($"\tpublic void Clear(int bit) => {ops}.Clear(this, bit);");
			sb.AppendLine($"\tpublic void Set(int bit, bool newVal) => {ops}.Set(this, bit, newVal);");
			sb.AppendLine($"\tpublic readonly int FindNextSetBit(int startBit) => {ops}.FindNextSetBit(this, startBit);");
			sb.AppendLine($"\tpublic void ClearAll() => {ops}.ClearAll(this);");
			sb.AppendLine($"\tpublic void SetAll() => {ops}.SetAll(this);");
			sb.AppendLine();
			sb.AppendLine($"\tpublic readonly bool Equals({name} other) => {ops}.Compare(this, other);");
			sb.AppendLine($"\tpublic override readonly bool Equals(object? obj) => obj is {name} other && Equals(other);");
			sb.AppendLine($"\tpublic override readonly int GetHashCode() => {ops}.Hash(this);");
			sb.AppendLine($"\tpublic static bool operator ==({name} a, {name} b) => a.Equals(b);");
			sb.AppendLine($"\tpublic static bool operator !=({name} a, {name} b) => !a.Equals(b);");
			sb.AppendLine("}");

			string hintName = model.Namespace != null ? $"{model.Namespace}.{name}.BitVec.g.cs" : $"{name}.BitVec.g.cs";
			spc.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
		}
	}
}
